package config

import (
	"charm.land/catwalk/pkg/catwalk"
)

// ApertisAIProvider returns the Apertis AI provider configuration.
// Apertis AI provides unified access to 500+ models across 30+ providers
// with free prompt caching, context compression, and auto-failover.
func ApertisAIProvider() catwalk.Provider {
	return catwalk.Provider{
		Name:                "Apertis AI",
		ID:                  "apertis",
		APIKey:              "$APERTIS_API_KEY",
		APIEndpoint:         "https://api.apertis.ai/v1",
		Type:                "openai-compat",
		DefaultLargeModelID: "claude-sonnet-4-6",
		DefaultSmallModelID: "gpt-4.1-mini",
		Models:              apertisAIModels(),
		DefaultHeaders:      map[string]string{},
	}
}

// apertisAIModels returns the list of models supported by Apertis AI.
// Apertis provides access to 500+ models; these are the most popular/latest ones.
func apertisAIModels() []catwalk.Model {
	return []catwalk.Model{
		// OpenAI models
		{
			ID:               "gpt-5.4",
			Name:             "GPT-5.4",
			CostPer1MIn:      2.5,
			CostPer1MOut:     10.0,
			ContextWindow:    400000,
			DefaultMaxTokens: 16384,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "gpt-5.2",
			Name:             "GPT-5.2",
			CostPer1MIn:      1.25,
			CostPer1MOut:     5.0,
			ContextWindow:    400000,
			DefaultMaxTokens: 16384,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "gpt-5",
			Name:             "GPT-5",
			CostPer1MIn:      1.25,
			CostPer1MOut:     10.0,
			ContextWindow:    400000,
			DefaultMaxTokens: 16384,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "gpt-4.1",
			Name:             "GPT-4.1",
			CostPer1MIn:      2.0,
			CostPer1MOut:     8.0,
			ContextWindow:    1047576,
			DefaultMaxTokens: 32768,
			CanReason:        false,
			SupportsImages:   true,
		},
		{
			ID:               "gpt-4.1-mini",
			Name:             "GPT-4.1 Mini",
			CostPer1MIn:      0.4,
			CostPer1MOut:     1.6,
			ContextWindow:    1047576,
			DefaultMaxTokens: 32768,
			CanReason:        false,
			SupportsImages:   true,
		},
		{
			ID:               "gpt-4.1-nano",
			Name:             "GPT-4.1 Nano",
			CostPer1MIn:      0.1,
			CostPer1MOut:     0.4,
			ContextWindow:    1047576,
			DefaultMaxTokens: 32768,
			CanReason:        false,
			SupportsImages:   true,
		},
		{
			ID:               "gpt-4o",
			Name:             "GPT-4o",
			CostPer1MIn:      2.5,
			CostPer1MOut:     10.0,
			ContextWindow:    128000,
			DefaultMaxTokens: 16384,
			CanReason:        false,
			SupportsImages:   true,
		},
		{
			ID:               "gpt-4o-mini",
			Name:             "GPT-4o Mini",
			CostPer1MIn:      0.15,
			CostPer1MOut:     0.6,
			ContextWindow:    128000,
			DefaultMaxTokens: 16384,
			CanReason:        false,
			SupportsImages:   true,
		},
		{
			ID:               "o3",
			Name:             "o3",
			CostPer1MIn:      10.0,
			CostPer1MOut:     40.0,
			ContextWindow:    200000,
			DefaultMaxTokens: 100000,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "o3-pro",
			Name:             "o3 Pro",
			CostPer1MIn:      20.0,
			CostPer1MOut:     80.0,
			ContextWindow:    200000,
			DefaultMaxTokens: 100000,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "o4-mini",
			Name:             "o4 Mini",
			CostPer1MIn:      1.1,
			CostPer1MOut:     4.4,
			ContextWindow:    200000,
			DefaultMaxTokens: 100000,
			CanReason:        true,
			SupportsImages:   false,
		},

		// Anthropic Claude models
		{
			ID:               "claude-opus-4-6",
			Name:             "Claude Opus 4.6",
			CostPer1MIn:      15.0,
			CostPer1MOut:     75.0,
			ContextWindow:    200000,
			DefaultMaxTokens: 32768,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "claude-sonnet-4-6",
			Name:             "Claude Sonnet 4.6",
			CostPer1MIn:      3.0,
			CostPer1MOut:     15.0,
			ContextWindow:    200000,
			DefaultMaxTokens: 32768,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "claude-sonnet-4-5",
			Name:             "Claude Sonnet 4.5",
			CostPer1MIn:      3.0,
			CostPer1MOut:     15.0,
			ContextWindow:    200000,
			DefaultMaxTokens: 32768,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "claude-sonnet-4-20250514",
			Name:             "Claude Sonnet 4",
			CostPer1MIn:      3.0,
			CostPer1MOut:     15.0,
			ContextWindow:    200000,
			DefaultMaxTokens: 32768,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "claude-opus-4-20250514",
			Name:             "Claude Opus 4",
			CostPer1MIn:      15.0,
			CostPer1MOut:     75.0,
			ContextWindow:    200000,
			DefaultMaxTokens: 32768,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "claude-haiku-4-20250414",
			Name:             "Claude Haiku 4",
			CostPer1MIn:      0.8,
			CostPer1MOut:     4.0,
			ContextWindow:    200000,
			DefaultMaxTokens: 32768,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "claude-3-5-sonnet-20241022",
			Name:             "Claude 3.5 Sonnet",
			CostPer1MIn:      3.0,
			CostPer1MOut:     15.0,
			ContextWindow:    200000,
			DefaultMaxTokens: 8192,
			CanReason:        false,
			SupportsImages:   true,
		},
		{
			ID:               "claude-3-5-haiku-20241022",
			Name:             "Claude 3.5 Haiku",
			CostPer1MIn:      0.8,
			CostPer1MOut:     4.0,
			ContextWindow:    200000,
			DefaultMaxTokens: 8192,
			CanReason:        false,
			SupportsImages:   false,
		},

		// Google Gemini models
		{
			ID:               "gemini-3-pro",
			Name:             "Gemini 3 Pro",
			CostPer1MIn:      1.25,
			CostPer1MOut:     10.0,
			ContextWindow:    1000000,
			DefaultMaxTokens: 65536,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "gemini-3-pro-preview",
			Name:             "Gemini 3 Pro Preview",
			CostPer1MIn:      1.25,
			CostPer1MOut:     10.0,
			ContextWindow:    1000000,
			DefaultMaxTokens: 65536,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "gemini-2.5-pro",
			Name:             "Gemini 2.5 Pro",
			CostPer1MIn:      1.25,
			CostPer1MOut:     10.0,
			ContextWindow:    1000000,
			DefaultMaxTokens: 65536,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "gemini-2.5-flash",
			Name:             "Gemini 2.5 Flash",
			CostPer1MIn:      0.15,
			CostPer1MOut:     0.6,
			ContextWindow:    1000000,
			DefaultMaxTokens: 65536,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "gemini-2.5-flash-lite",
			Name:             "Gemini 2.5 Flash Lite",
			CostPer1MIn:      0.0375,
			CostPer1MOut:     0.15,
			ContextWindow:    1000000,
			DefaultMaxTokens: 65536,
			CanReason:        false,
			SupportsImages:   true,
		},

		// Meta Llama models
		{
			ID:               "llama-4-maverick",
			Name:             "Llama 4 Maverick",
			CostPer1MIn:      0.2,
			CostPer1MOut:     0.6,
			ContextWindow:    10000000,
			DefaultMaxTokens: 32768,
			CanReason:        false,
			SupportsImages:   true,
		},
		{
			ID:               "llama-4-scout",
			Name:             "Llama 4 Scout",
			CostPer1MIn:      0.12,
			CostPer1MOut:     0.3,
			ContextWindow:    10000000,
			DefaultMaxTokens: 32768,
			CanReason:        false,
			SupportsImages:   true,
		},
		{
			ID:               "llama-3.3-70b-instruct",
			Name:             "Llama 3.3 70B Instruct",
			CostPer1MIn:      0.59,
			CostPer1MOut:     0.79,
			ContextWindow:    131072,
			DefaultMaxTokens: 8192,
			CanReason:        false,
			SupportsImages:   false,
		},
		{
			ID:               "llama-3.1-405b-instruct",
			Name:             "Llama 3.1 405B Instruct",
			CostPer1MIn:      2.0,
			CostPer1MOut:     2.0,
			ContextWindow:    131072,
			DefaultMaxTokens: 8192,
			CanReason:        false,
			SupportsImages:   false,
		},

		// Mistral models
		{
			ID:               "mistral-large-2",
			Name:             "Mistral Large 2",
			CostPer1MIn:      2.0,
			CostPer1MOut:     6.0,
			ContextWindow:    131072,
			DefaultMaxTokens: 8192,
			CanReason:        false,
			SupportsImages:   false,
		},
		{
			ID:               "mistral-small",
			Name:             "Mistral Small",
			CostPer1MIn:      0.2,
			CostPer1MOut:     0.6,
			ContextWindow:    131072,
			DefaultMaxTokens: 8192,
			CanReason:        false,
			SupportsImages:   false,
		},
		{
			ID:               "pixtral-large",
			Name:             "Pixtral Large",
			CostPer1MIn:      2.0,
			CostPer1MOut:     6.0,
			ContextWindow:    131072,
			DefaultMaxTokens: 8192,
			CanReason:        false,
			SupportsImages:   true,
		},

		// DeepSeek models
		{
			ID:               "deepseek-r1",
			Name:             "DeepSeek R1",
			CostPer1MIn:      0.5,
			CostPer1MOut:     2.0,
			ContextWindow:    64000,
			DefaultMaxTokens: 8192,
			CanReason:        true,
			SupportsImages:   false,
		},
		{
			ID:               "deepseek-v3",
			Name:             "DeepSeek V3",
			CostPer1MIn:      0.27,
			CostPer1MOut:     1.1,
			ContextWindow:    64000,
			DefaultMaxTokens: 8192,
			CanReason:        false,
			SupportsImages:   false,
		},
		{
			ID:               "deepseek-chat",
			Name:             "DeepSeek Chat",
			CostPer1MIn:      0.27,
			CostPer1MOut:     1.1,
			ContextWindow:    64000,
			DefaultMaxTokens: 8192,
			CanReason:        false,
			SupportsImages:   false,
		},

		// Qwen models
		{
			ID:               "qwen3-235b-a22b",
			Name:             "Qwen3 235B A22B",
			CostPer1MIn:      0.5,
			CostPer1MOut:     2.0,
			ContextWindow:    131072,
			DefaultMaxTokens: 8192,
			CanReason:        true,
			SupportsImages:   false,
		},
		{
			ID:               "qwen3-30b-a3b",
			Name:             "Qwen3 30B A3B",
			CostPer1MIn:      0.1,
			CostPer1MOut:     0.3,
			ContextWindow:    131072,
			DefaultMaxTokens: 8192,
			CanReason:        true,
			SupportsImages:   false,
		},
		{
			ID:               "qwen3-coder",
			Name:             "Qwen3 Coder",
			CostPer1MIn:      0.5,
			CostPer1MOut:     2.0,
			ContextWindow:    131072,
			DefaultMaxTokens: 8192,
			CanReason:        true,
			SupportsImages:   false,
		},
		{
			ID:               "qwen2.5-72b-instruct",
			Name:             "Qwen 2.5 72B Instruct",
			CostPer1MIn:      0.5,
			CostPer1MOut:     1.5,
			ContextWindow:    131072,
			DefaultMaxTokens: 8192,
			CanReason:        false,
			SupportsImages:   false,
		},
		{
			ID:               "qwen2.5-coder-32b-instruct",
			Name:             "Qwen 2.5 Coder 32B Instruct",
			CostPer1MIn:      0.2,
			CostPer1MOut:     0.6,
			ContextWindow:    131072,
			DefaultMaxTokens: 8192,
			CanReason:        false,
			SupportsImages:   false,
		},

		// xAI Grok models
		{
			ID:               "grok-4",
			Name:             "Grok 4",
			CostPer1MIn:      3.0,
			CostPer1MOut:     15.0,
			ContextWindow:    256000,
			DefaultMaxTokens: 32768,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "grok-3",
			Name:             "Grok 3",
			CostPer1MIn:      3.0,
			CostPer1MOut:     15.0,
			ContextWindow:    131072,
			DefaultMaxTokens: 8192,
			CanReason:        true,
			SupportsImages:   false,
		},
		{
			ID:               "grok-3-mini",
			Name:             "Grok 3 Mini",
			CostPer1MIn:      0.3,
			CostPer1MOut:     0.5,
			ContextWindow:    131072,
			DefaultMaxTokens: 8192,
			CanReason:        true,
			SupportsImages:   false,
		},

		// MiniMax models
		{
			ID:               "minimax-m2.1",
			Name:             "MiniMax M2.1",
			CostPer1MIn:      0.2,
			CostPer1MOut:     1.0,
			ContextWindow:    1000000,
			DefaultMaxTokens: 8192,
			CanReason:        false,
			SupportsImages:   false,
		},

		// Kimi models
		{
			ID:               "kimi-k2.5",
			Name:             "Kimi K2.5",
			CostPer1MIn:      0.5,
			CostPer1MOut:     2.0,
			ContextWindow:    131072,
			DefaultMaxTokens: 8192,
			CanReason:        true,
			SupportsImages:   false,
		},

		// Cohere models
		{
			ID:               "command-a",
			Name:             "Command A",
			CostPer1MIn:      2.5,
			CostPer1MOut:     10.0,
			ContextWindow:    256000,
			DefaultMaxTokens: 8192,
			CanReason:        false,
			SupportsImages:   false,
		},
		{
			ID:               "command-r-plus",
			Name:             "Command R Plus",
			CostPer1MIn:      2.5,
			CostPer1MOut:     10.0,
			ContextWindow:    128000,
			DefaultMaxTokens: 4096,
			CanReason:        false,
			SupportsImages:   false,
		},

		// Perplexity models
		{
			ID:               "sonar-pro",
			Name:             "Sonar Pro",
			CostPer1MIn:      3.0,
			CostPer1MOut:     15.0,
			ContextWindow:    128000,
			DefaultMaxTokens: 8192,
			CanReason:        false,
			SupportsImages:   false,
		},
		{
			ID:               "sonar",
			Name:             "Sonar",
			CostPer1MIn:      1.0,
			CostPer1MOut:     1.0,
			ContextWindow:    128000,
			DefaultMaxTokens: 8192,
			CanReason:        false,
			SupportsImages:   false,
		},

		// Amazon Nova models
		{
			ID:               "nova-pro",
			Name:             "Amazon Nova Pro",
			CostPer1MIn:      0.8,
			CostPer1MOut:     3.2,
			ContextWindow:    300000,
			DefaultMaxTokens: 8192,
			CanReason:        false,
			SupportsImages:   true,
		},
		{
			ID:               "nova-lite",
			Name:             "Amazon Nova Lite",
			CostPer1MIn:      0.06,
			CostPer1MOut:     0.24,
			ContextWindow:    300000,
			DefaultMaxTokens: 8192,
			CanReason:        false,
			SupportsImages:   true,
		},

		// Microsoft Phi models
		{
			ID:               "phi-4",
			Name:             "Phi 4",
			CostPer1MIn:      0.07,
			CostPer1MOut:     0.14,
			ContextWindow:    131072,
			DefaultMaxTokens: 8192,
			CanReason:        false,
			SupportsImages:   false,
		},

		// Alibaba QwQ models
		{
			ID:               "qwq-32b",
			Name:             "QwQ 32B",
			CostPer1MIn:      0.2,
			CostPer1MOut:     0.6,
			ContextWindow:    131072,
			DefaultMaxTokens: 8192,
			CanReason:        true,
			SupportsImages:   false,
		},
	}
}
