package config

import (
	"charm.land/catwalk/pkg/catwalk"
)

func CrofAIProvider() catwalk.Provider {
	return catwalk.Provider{
		Name:                "CrofAI",
		ID:                  "crofai",
		APIKey:              "$CROFAI_API_KEY",
		APIEndpoint:         "https://crof.ai/v1",
		Type:                "openai-compat",
		DefaultLargeModelID: "glm-5",
		DefaultSmallModelID: "deepseek-v3.2",
		Models:              crofAIModels(),
		DefaultHeaders:      map[string]string{},
	}
}

func crofAIModels() []catwalk.Model {
	return []catwalk.Model{
		{
			ID:               "kimi-k2.5",
			Name:             "Kimi K2.5",
			CostPer1MIn:      0.35,
			CostPer1MOut:     1.70,
			ContextWindow:    262144,
			DefaultMaxTokens: 262144,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "greg",
			Name:             "Greg",
			CostPer1MIn:      0.30,
			CostPer1MOut:     0.30,
			ContextWindow:    200000,
			DefaultMaxTokens: 200000,
			CanReason:        true,
			SupportsImages:   false,
		},
		{
			ID:               "kimi-k2.5-lightning",
			Name:             "Kimi K2.5 Lightning",
			CostPer1MIn:      1.00,
			CostPer1MOut:     3.00,
			ContextWindow:    131072,
			DefaultMaxTokens: 32768,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "glm-5.1",
			Name:             "GLM-5.1",
			CostPer1MIn:      0.50,
			CostPer1MOut:     2.10,
			ContextWindow:    202752,
			DefaultMaxTokens: 202752,
			CanReason:        true,
			SupportsImages:   false,
		},
		{
			ID:               "glm-5.1-precision",
			Name:             "GLM-5.1 Precision",
			CostPer1MIn:      0.70,
			CostPer1MOut:     2.50,
			ContextWindow:    202752,
			DefaultMaxTokens: 202752,
			CanReason:        true,
			SupportsImages:   false,
		},
		{
			ID:               "glm-5",
			Name:             "GLM-5",
			CostPer1MIn:      0.48,
			CostPer1MOut:     1.90,
			ContextWindow:    202752,
			DefaultMaxTokens: 202752,
			CanReason:        true,
			SupportsImages:   false,
		},
		{
			ID:               "glm-4.7",
			Name:             "GLM-4.7",
			CostPer1MIn:      0.25,
			CostPer1MOut:     1.10,
			ContextWindow:    202752,
			DefaultMaxTokens: 202752,
			CanReason:        true,
			SupportsImages:   false,
		},
		{
			ID:               "glm-4.7-flash",
			Name:             "GLM-4.7 Flash",
			CostPer1MIn:      0.0,
			CostPer1MOut:     0.0,
			ContextWindow:    202752,
			DefaultMaxTokens: 131072,
			CanReason:        false,
			SupportsImages:   false,
		},
		{
			ID:               "gemma-4-31b-it",
			Name:             "Gemma 4 31B IT",
			CostPer1MIn:      0.10,
			CostPer1MOut:     0.30,
			ContextWindow:    262144,
			DefaultMaxTokens: 262144,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "minimax-m2.5",
			Name:             "MiniMax M2.5",
			CostPer1MIn:      0.11,
			CostPer1MOut:     0.95,
			ContextWindow:    204800,
			DefaultMaxTokens: 131072,
			CanReason:        true,
			SupportsImages:   false,
		},
		{
			ID:               "qwen3.5-397b-a17b",
			Name:             "Qwen 3.5 397B A17B",
			CostPer1MIn:      0.35,
			CostPer1MOut:     1.75,
			ContextWindow:    262144,
			DefaultMaxTokens: 262144,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "qwen3.5-9b",
			Name:             "Qwen 3.5 9B",
			CostPer1MIn:      0.0,
			CostPer1MOut:     0.0,
			ContextWindow:    262144,
			DefaultMaxTokens: 262144,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "qwen3.5-9b-chat",
			Name:             "Qwen 3.5 9B Chat",
			CostPer1MIn:      0.04,
			CostPer1MOut:     0.15,
			ContextWindow:    262144,
			DefaultMaxTokens: 262144,
			CanReason:        false,
			SupportsImages:   false,
		},
		{
			ID:               "deepseek-v3.2",
			Name:             "DeepSeek V3.2",
			CostPer1MIn:      0.28,
			CostPer1MOut:     0.38,
			ContextWindow:    163840,
			DefaultMaxTokens: 163840,
			CanReason:        true,
			SupportsImages:   false,
		},
	}
}
