package config

import (
	"charm.land/catwalk/pkg/catwalk"
)

// OpenCodeZenProvider returns the OpenCode Zen/Go provider configuration.
// OpenCode Zen and Go are multi-model providers offering access to various LLMs
// through a unified OpenAI-compatible API endpoint. Zen is the pay-as-you-go
// plan, while Go is the low-cost subscription plan - both use the same API.
func OpenCodeZenProvider() catwalk.Provider {
	return catwalk.Provider{
		Name:                "OpenCode Zen/Go",
		ID:                  "opencode-zen",
		APIKey:              "$ZEN_API_KEY",
		APIEndpoint:         "https://opencode.ai/zen/v1",
		Type:                "openai-compat",
		DefaultLargeModelID: "claude-opus-4-6",
		DefaultSmallModelID: "claude-haiku-4-5",
		Models:              openCodeZenModels(),
		DefaultHeaders:      map[string]string{},
	}
}

// openCodeZenModels returns the list of models supported by OpenCode Zen.
// Models include Claude, Gemini, GPT, GLM, MiniMax, and Kimi variants.
func openCodeZenModels() []catwalk.Model {
	return []catwalk.Model{
		// Claude Models
		{
			ID:               "claude-opus-4-6",
			Name:             "Claude Opus 4.6",
			CostPer1MIn:      15.0,
			CostPer1MOut:     75.0,
			ContextWindow:    200000,
			DefaultMaxTokens: 8192,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "claude-opus-4-5",
			Name:             "Claude Opus 4.5",
			CostPer1MIn:      15.0,
			CostPer1MOut:     75.0,
			ContextWindow:    200000,
			DefaultMaxTokens: 8192,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "claude-opus-4-1",
			Name:             "Claude Opus 4.1",
			CostPer1MIn:      15.0,
			CostPer1MOut:     75.0,
			ContextWindow:    200000,
			DefaultMaxTokens: 8192,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "claude-sonnet-4-6",
			Name:             "Claude Sonnet 4.6",
			CostPer1MIn:      3.0,
			CostPer1MOut:     15.0,
			ContextWindow:    200000,
			DefaultMaxTokens: 8192,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "claude-sonnet-4-5",
			Name:             "Claude Sonnet 4.5",
			CostPer1MIn:      3.0,
			CostPer1MOut:     15.0,
			ContextWindow:    200000,
			DefaultMaxTokens: 8192,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "claude-sonnet-4",
			Name:             "Claude Sonnet 4",
			CostPer1MIn:      3.0,
			CostPer1MOut:     15.0,
			ContextWindow:    200000,
			DefaultMaxTokens: 8192,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "claude-3-5-haiku",
			Name:             "Claude 3.5 Haiku",
			CostPer1MIn:      0.8,
			CostPer1MOut:     4.0,
			ContextWindow:    200000,
			DefaultMaxTokens: 4096,
			CanReason:        false,
			SupportsImages:   false,
		},
		{
			ID:               "claude-haiku-4-5",
			Name:             "Claude Haiku 4.5",
			CostPer1MIn:      0.8,
			CostPer1MOut:     4.0,
			ContextWindow:    200000,
			DefaultMaxTokens: 4096,
			CanReason:        false,
			SupportsImages:   false,
		},
		// Gemini Models
		{
			ID:               "gemini-3.1-pro",
			Name:             "Gemini 3.1 Pro",
			CostPer1MIn:      3.5,
			CostPer1MOut:     10.5,
			ContextWindow:    2000000,
			DefaultMaxTokens: 8192,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "gemini-3-pro",
			Name:             "Gemini 3 Pro",
			CostPer1MIn:      3.5,
			CostPer1MOut:     10.5,
			ContextWindow:    1000000,
			DefaultMaxTokens: 8192,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "gemini-3-flash",
			Name:             "Gemini 3 Flash",
			CostPer1MIn:      0.35,
			CostPer1MOut:     1.05,
			ContextWindow:    1000000,
			DefaultMaxTokens: 8192,
			CanReason:        true,
			SupportsImages:   true,
		},
		// GPT Models
		{
			ID:               "gpt-5.4-pro",
			Name:             "GPT-5.4 Pro",
			CostPer1MIn:      30.0,
			CostPer1MOut:     180.0,
			ContextWindow:    1050000,
			DefaultMaxTokens: 128000,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "gpt-5.4",
			Name:             "GPT-5.4",
			CostPer1MIn:      2.5,
			CostPer1MOut:     15.0,
			ContextWindow:    1050000,
			DefaultMaxTokens: 128000,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "gpt-5.3-codex-spark",
			Name:             "GPT-5.3 Codex Spark",
			CostPer1MIn:      1.75,
			CostPer1MOut:     14.0,
			ContextWindow:    400000,
			DefaultMaxTokens: 128000,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "gpt-5.3-codex",
			Name:             "GPT-5.3 Codex",
			CostPer1MIn:      1.75,
			CostPer1MOut:     14.0,
			ContextWindow:    400000,
			DefaultMaxTokens: 128000,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "gpt-5.2",
			Name:             "GPT-5.2",
			CostPer1MIn:      1.75,
			CostPer1MOut:     14.0,
			ContextWindow:    400000,
			DefaultMaxTokens: 128000,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "gpt-5.2-codex",
			Name:             "GPT-5.2 Codex",
			CostPer1MIn:      1.75,
			CostPer1MOut:     14.0,
			ContextWindow:    400000,
			DefaultMaxTokens: 128000,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "gpt-5.1",
			Name:             "GPT-5.1",
			CostPer1MIn:      1.25,
			CostPer1MOut:     10.0,
			ContextWindow:    400000,
			DefaultMaxTokens: 128000,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "gpt-5.1-codex-max",
			Name:             "GPT-5.1 Codex Max",
			CostPer1MIn:      1.25,
			CostPer1MOut:     10.0,
			ContextWindow:    400000,
			DefaultMaxTokens: 128000,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "gpt-5.1-codex",
			Name:             "GPT-5.1 Codex",
			CostPer1MIn:      1.25,
			CostPer1MOut:     10.0,
			ContextWindow:    400000,
			DefaultMaxTokens: 128000,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "gpt-5.1-codex-mini",
			Name:             "GPT-5.1 Codex Mini",
			CostPer1MIn:      0.25,
			CostPer1MOut:     2.0,
			ContextWindow:    400000,
			DefaultMaxTokens: 128000,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "gpt-5",
			Name:             "GPT-5",
			CostPer1MIn:      1.25,
			CostPer1MOut:     10.0,
			ContextWindow:    400000,
			DefaultMaxTokens: 128000,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "gpt-5-codex",
			Name:             "GPT-5 Codex",
			CostPer1MIn:      1.25,
			CostPer1MOut:     10.0,
			ContextWindow:    400000,
			DefaultMaxTokens: 128000,
			CanReason:        true,
			SupportsImages:   true,
		},
		{
			ID:               "gpt-5-nano",
			Name:             "GPT-5 Nano",
			CostPer1MIn:      0.05,
			CostPer1MOut:     0.4,
			ContextWindow:    400000,
			DefaultMaxTokens: 128000,
			CanReason:        true,
			SupportsImages:   true,
		},
		// GLM Models
		{
			ID:               "glm-5",
			Name:             "GLM-5",
			CostPer1MIn:      1.0,
			CostPer1MOut:     3.2,
			ContextWindow:    204800,
			DefaultMaxTokens: 65536,
			CanReason:        true,
			SupportsImages:   false,
		},
		{
			ID:               "glm-4.7",
			Name:             "GLM-4.7",
			CostPer1MIn:      0.42,
			CostPer1MOut:     2.2,
			ContextWindow:    204800,
			DefaultMaxTokens: 102400,
			CanReason:        true,
			SupportsImages:   false,
		},
		{
			ID:               "glm-4.6",
			Name:             "GLM-4.6",
			CostPer1MIn:      0.39,
			CostPer1MOut:     1.9,
			ContextWindow:    204800,
			DefaultMaxTokens: 102400,
			CanReason:        true,
			SupportsImages:   false,
		},
		// MiniMax Models
		{
			ID:               "minimax-m2.5",
			Name:             "MiniMax M2.5",
			CostPer1MIn:      0.5,
			CostPer1MOut:     2.0,
			ContextWindow:    100000,
			DefaultMaxTokens: 8192,
			CanReason:        true,
			SupportsImages:   false,
		},
		{
			ID:               "minimax-m2.5-free",
			Name:             "MiniMax M2.5 Free",
			CostPer1MIn:      0.0,
			CostPer1MOut:     0.0,
			ContextWindow:    100000,
			DefaultMaxTokens: 8192,
			CanReason:        true,
			SupportsImages:   false,
		},
		{
			ID:               "minimax-m2.1",
			Name:             "MiniMax M2.1",
			CostPer1MIn:      0.3,
			CostPer1MOut:     1.2,
			ContextWindow:    100000,
			DefaultMaxTokens: 8192,
			CanReason:        true,
			SupportsImages:   false,
		},
		{
			ID:               "minimax-m2.7",
			Name:             "MiniMax M2.7",
			CostPer1MIn:      0.3,
			CostPer1MOut:     1.2,
			ContextWindow:    204800,
			DefaultMaxTokens: 131072,
			CanReason:        true,
			SupportsImages:   false,
		},
		// Kimi Models
		{
			ID:               "kimi-k2.5",
			Name:             "Kimi K2.5",
			CostPer1MIn:      0.5,
			CostPer1MOut:     2.0,
			ContextWindow:    256000,
			DefaultMaxTokens: 8192,
			CanReason:        true,
			SupportsImages:   false,
		},
		{
			ID:               "kimi-k2",
			Name:             "Kimi K2",
			CostPer1MIn:      0.3,
			CostPer1MOut:     1.2,
			ContextWindow:    256000,
			DefaultMaxTokens: 8192,
			CanReason:        true,
			SupportsImages:   false,
		},
		{
			ID:               "kimi-k2-thinking",
			Name:             "Kimi K2 Thinking",
			CostPer1MIn:      0.3,
			CostPer1MOut:     1.2,
			ContextWindow:    256000,
			DefaultMaxTokens: 8192,
			CanReason:        true,
			SupportsImages:   false,
		},
		// Free Models
		{
			ID:               "mimo-v2-flash-free",
			Name:             "Mimo V2 Flash (Free)",
			CostPer1MIn:      0.0,
			CostPer1MOut:     0.0,
			ContextWindow:    128000,
			DefaultMaxTokens: 4096,
			CanReason:        false,
			SupportsImages:   false,
		},
		{
			ID:               "trinity-large-preview-free",
			Name:             "Trinity Large Preview (Free)",
			CostPer1MIn:      0.0,
			CostPer1MOut:     0.0,
			ContextWindow:    128000,
			DefaultMaxTokens: 4096,
			CanReason:        false,
			SupportsImages:   false,
		},
		{
			ID:               "big-pickle",
			Name:             "Big Pickle (Free)",
			CostPer1MIn:      0.0,
			CostPer1MOut:     0.0,
			ContextWindow:    128000,
			DefaultMaxTokens: 4096,
			CanReason:        false,
			SupportsImages:   false,
		},
		{
			ID:               "nemotron-3-super-free",
			Name:             "Nemotron 3 Super (Free)",
			CostPer1MIn:      0.0,
			CostPer1MOut:     0.0,
			ContextWindow:    128000,
			DefaultMaxTokens: 4096,
			CanReason:        false,
			SupportsImages:   false,
		},
	}
}
